export default defineAppConfig({
  pages: [
    // SSO 回调页。登录页已经搬到认证中心（call-auth），不在本应用里了
    'pages/auth/callback/index',
    'pages/games/index',
    'pages/my-games/index',
    'pages/game-detail/index',
    'pages/score-deposit/index',
    'pages/score-withdraw/index',
    'pages/chip-count/index',
    'pages/profile/index',
    'pages/create-game/index',
    'pages/leaderboard/index',
    'pages/history/index',
    'pages/transaction-records/index',
    'pages/score-request-deposit/index',
    'pages/score-request-withdraw/index',
    'pages/score-request-review/index',
    'pages/my-score-requests/index',
    'pages/messages/index',
    'pages/message-detail/index',
    'pages/reviews/index',
    'pages/review-create/index',
    'pages/review-detail/index',
    'pages/review-profile/index',
    'pages/opponents/index',
    'pages/opponent-detail/index',
    'pages/settings/index',
    'pages/settings-blind/index',
    'pages/settings-model/index',
    'pages/odds-drill/index',
  ],
  // 入口页就是默认落地页。以前这里是登录页，现在登录归认证中心 ——
  // 未登录时由路由守卫（RequireAuth）跳 /sso，不需要一个专门的入口页
  entryPagePath: 'pages/games/index',
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#F8F9FC',
    navigationBarTitleText: 'Call游戏管理',
    navigationBarTextStyle: 'black',
  },
});
