export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/games/index',
    'pages/my-games/index',
    'pages/game-detail/index',
    'pages/score-deposit/index',
    'pages/score-withdraw/index',
    'pages/chip-count/index',
    'pages/profile/index',
    'pages/create-game/index',
    'pages/leaderboard/index',
    'pages/history/index',
    'pages/transaction-records/index',
    'pages/score-request-deposit/index',
    'pages/score-request-withdraw/index',
    'pages/score-request-review/index',
    'pages/my-score-requests/index',
    'pages/messages/index',
    'pages/reviews/index',
    'pages/review-create/index',
    'pages/review-detail/index',
  ],
  entryPagePath: 'pages/login/index',
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#F8F9FC',
    navigationBarTitleText: 'Call游戏管理',
    navigationBarTextStyle: 'black',
  },
});
